config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/search' => "pages#search"
  resources :users
  resources :cafes do
    resources :rating_cafes
  end
  resources :roasters do
    resources :roaster_ratings
  end
  get '/login' => 'session#new' # show login form
  post '/login' => 'session#create' # form submits, performs login, redirects
  delete '/login' => 'session#destroy' #logout link goes here, perform logout, redirect
end

app/models/roaster.rb
class Roaster < ApplicationRecord
    has_many :cafes
    has_many :roaster_ratings
    has_many :users, through: 'roaster_ratings'
end

app/controllers/roasters_controller.rb
class RoastersController < ApplicationController
  before_action :check_if_logged_in, except: [:index, :show]
  
  def new
    @roaster = Roaster.new
  end

  def create
    Roaster.create roaster_params

    redirect_to roasters_path
  end

  def index
    @roasters = Roaster.all
  end

  def show
    @roaster = Roaster.find params[:id]
  end

  def edit
    @roaster = Roaster.find params[:id]
  end

  def update
    roaster = Roaster.find params[:id]
    roaster.update! roaster_params
    redirect_to roaster_path(params[:id])
  end

  def destroy
    Roaster.destroy params[:id]
    redirect_to roasters_path
  end

  private
  def roaster_params
    params.require(:roaster).permit(
      :name,
      :address
    )
  end
end

app/helpers/roasters_helper.rb
module RoastersHelper
end

app/views/roasters/_form.html.erb
<%= form_with model: @roaster, local: true do |f| %>

    <%= f.label :name, 'Roaster Name'%>
    <br>
    <%= f.text_field :name %>
    <br><br>
    
    <%= f.label :address %>
    <br>
    <%= f.text_field :address %>
    <br><br>

    <%= f.submit %>

<% end %>

app/views/roasters/edit.html.erb
<h3>Edit Roaster: <%= @roaster.name %></h3>

<%= render partial: 'form' %>

app/views/roasters/index.html.erb
<div class="index-header">
    <h2>All Roasters</h2>
</div>
<ul>
    <% @roasters.each do |r|%>
        <li>
            <%= link_to r.name, roaster_path(r) %> - <%= r.address %>
        </li>
        <br>
    <% end%>
</ul>

app/views/roasters/new.html.erb
<h3 class="name">Add New Roaster</h3>

<%= render partial: 'form' %>

app/views/roasters/show.html.erb
<h3 class="name">
    <%= @roaster.name %>
</h3>
<div class="address">
    <p>
        <%= @roaster.address %>
    </p>
</div>
<hr>
Cafes Supplied:
<ul>
    <% @roaster.cafes.each do |c|%>
        <li>
            <%= link_to c.name, cafe_path(c) %>
        </li>
    <% end%>
</ul>

<hr>

<div class="new-review">
    <% if @current_user.present? %> 
        <%= link_to "Add new Rating", new_roaster_roaster_rating_path(@roaster) %>
    <% end %>
</div>

<div class="show-visits">
    <p>
        Recent Reviews:
        <%= render @roaster.roaster_ratings %>
    </p>
</div>
<hr>
<div class="map">
    <iframe width="600" height="450" style="border:0" loading="lazy" allowfullscreen src="https://www.google.com/maps/embed/v1/place?q=<%= @roaster.address %>&key=AIzaSyCdE635lhPuKadi5SMfYwPrwZkG27OZ-d4"></iframe>
</div>
<div class="admin-controls">
    <% if @current_user.present? && @current_user.admin %>
        <%= link_to 'Edit', edit_roaster_path(@roaster.id) %>
        |
        <%= link_to 'Delete', roaster_path(@roaster), method: 'delete' %>
    <% end%>
</div>