config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/search' => "pages#search"
  resources :users
  resources :cafes do
    resources :rating_cafes
  end
  resources :roasters do
    resources :roaster_ratings
  end
  get '/login' => 'session#new' # show login form
  post '/login' => 'session#create' # form submits, performs login, redirects
  delete '/login' => 'session#destroy' #logout link goes here, perform logout, redirect
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, uniqueness: true

    has_many :rating_cafes
    has_many :roaster_ratings
    has_many :cafes, through: 'cafe_ratings'
    has_many :roasters, through: 'roaster_ratings'
    has_many :following_relationships, class_name: 'Follow', foreign_key: 'follower_id'
    has_many :followed_relationships, class_name: 'Follow', foreign_key: 'followed_id'

    has_many :following, through: :following_relationships, source: :followed
    has_many :followers, through: :followed_relationships, source: :follower

    def follow_safe other_user
        if self.following.include? other_user
            return false
        else
            self.following << other_user
            return true
        end
    end 

    def following_users
        User.where user: self.following        
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    
    if params[:user][:photo_url].present?
      response = Cloudinary::Uploader.upload params[:user][:photo_url]
      @user.photo_url = response['public_id']
    end
    
    @user.save
    
    if @user.persisted?
      session[:user_id] = @user.id
      redirect_to users_path
    else
      flash[:error] = 'Invalid email or password'
      render :new
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    user = User.find params[:id]
    user.update! user_params
    redirect_to user_path(params[:id])
  end

  def destroy
    User.destroy params[:id]
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(
      :email,
      :name,
      :city,
      :suburb,
      :photo_url,
      :password,
      :password_confirmation
    )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
 <%= form_with model: @user, local: true, html: {multipart: true} do |f| %>
 
    <%= f.label :name %>
    <br>
    <%= f.text_field :name %>
    <br><br>
    
    <%= f.label :city %>
    <br>
    <%= f.text_field :city %>
    <br><br>
    
    <%= f.label :suburb %>
    <br>
    <%= f.text_field :suburb %>
    <br><br>
  
    <%= f.label :photo_url %>
    <br>
    <%= f.file_field :photo_url %>
    <br><br>


    <%= f.submit %>

<% end %>

app/views/users/index.html.erb
<div class="index-header">    
    <h2>All Users</h2>
</div>
<div class="user-index">
    <ul>
        <% @users.each do |u|%>
            <li class="user-list">
                <div class="index-img">
                    <%= link_to cl_image_tag(u.photo_url), user_path(u) %>
                </div>
                <div class="index-name">
                    <%= link_to u.name, user_path(u) %> (<%= u.suburb %>, <%= u.city %>) 
                </div>
                <hr>
            </li>
        <% end%>
    </ul>
</div>

app/views/users/new.html.erb
<%= form_with model: @user, local: true, html: {multipart: true} do |f| %>

    <%= f.label :email, "Email Address" %>
    <br>
    <%= f.text_field :email %>
    <br><br>

    <%= f.label :password %>
    <br>
    <%= f.password_field :password %>
    <br><br>

    <%= f.label :password, "Confirm Password" %>
    <br>
    <%= f.password_field :password_confirmation %>
    <br><br>
 
    <%= f.label :name %>
    <br>
    <%= f.text_field :name %>
    <br><br>
    
    <%= f.label :city %>
    <br>
    <%= f.text_field :city %>
    <br><br>
    
    <%= f.label :suburb %>
    <br>
    <%= f.text_field :suburb %>
    <br><br>
  
    <%= f.label :photo_url %>
    <br>
    <%= f.file_field :photo_url %>
    <br><br>


    <%= f.submit %>

<% end %>

app/views/users/show.html.erb
<div class="user-container">
    <div class="img-wrapper">
        <%= cl_image_tag @user.photo_url %>
    </div>
    <h1><%= @user.name %></h1>
    <p><%= @user.suburb %>, <%= @user.city %></p>
</div>

<hr class>

<div class="cafe-reviews">
    <h4>
    Recent Cafe Reviews:
    </h4>
    <% @user.rating_cafes.each do |r| %>
        <% cafe = Cafe.find r.cafe_id %>
        <%= link_to "#{cafe.name}", cafe_path(r.cafe_id) %>
        <br>
        Rating:
        <%= r.rating %> / 5
        <br>
        "<%= r.review %>"
        <br><br>
    <% end%>
</div>
<div class="roaster-reviews">
    <h4>
    Recent Roaster Reviews:
    </h4>
    <% @user.roaster_ratings.each do |r| %>
        <% roaster = Roaster.find r.roaster_id %>
        <%= link_to "#{roaster.name}", roaster_path(r.roaster_id) %>
        <br>
        Rating:
        <%= r.rating %> / 5
        <br>
        "<%= r.review %>"
        <br><br>
    <% end%>
</div>

<div class="vl"></div>


<div class="admin-controls">
    <% if @current_user == @user %>
        <%= link_to 'Edit', edit_user_path(@user) %>
        |
        <%= link_to 'Delete', user_path(@user), method: 'delete' %>
    <% end%>
</div>