config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/search' => "pages#search"
  resources :users
  resources :cafes do
    resources :rating_cafes
  end
  resources :roasters do
    resources :roaster_ratings
  end
  get '/login' => 'session#new' # show login form
  post '/login' => 'session#create' # form submits, performs login, redirects
  delete '/login' => 'session#destroy' #logout link goes here, perform logout, redirect
end

app/models/cafe.rb
class Cafe < ApplicationRecord
    belongs_to :roaster, optional: true
    has_many :rating_cafes
    has_many :users, through: 'cafe_ratings'
end

app/controllers/cafes_controller.rb
class CafesController < ApplicationController
  
  before_action :check_if_logged_in, except: [:index, :show]
  
  def new
    @cafe = Cafe.new
  end

  def create
    Cafe.create cafe_params

    redirect_to cafes_path
  end

  def index
    @cafes = Cafe.all
  end

  def show
    @cafe = Cafe.find params[:id]
  end

  def edit
    @cafe = Cafe.find params[:id]
  end

  def update
    cafe = Cafe.find params[:id]
    cafe.update! cafe_params
    redirect_to cafe_path(params[:id])
  end

  def destroy
    Cafe.destroy params[:id]
    redirect_to cafes_path
  end

  private
  def cafe_params
    params.require(:cafe).permit(
      :name,
      :address,
      :roaster_id
    )
  end
end

app/helpers/cafes_helper.rb
module CafesHelper
end

app/views/cafes/_form.html.erb
<% if @cafe.errors.any?%>
    <ul>
        <% @cafe.errors.full_messages.each do |e| %>
        <li>
            <%= e %>
        </li>
        <% end %>
    </ul>
<% end %>

<%= form_with model: @cafe, local: true do |f| %>

    <%= f.label :name, 'Cafe Name'%>
    <br>
    <%= f.text_field :name %>
    <br><br>
    
    <%= f.label :address %>
    <br>
    <%= f.text_field :address %>
    <br><br>

    <%= f.label :roaster_id, 'Roaster (leave blank if none)' %>
    <br>
    <%= f.collection_select :roaster_id, Roaster.all, :id, :name, include_blank: true %>
    <br><br>

    <%= f.submit %>

<% end %>

app/views/cafes/edit.html.erb
<h3>Edit Cafe: <%= @cafe.name %></h3>

<%= render partial: 'form' %>

app/views/cafes/index.html.erb
<div class="index-header">
    <h2>All Cafes</h2>
</div>
<ul>
    <% @cafes.each do |c|%>
        <li>
            <%= link_to c.name, cafe_path(c) %> - <%= c.address %>
        </li>
        <br>
    <% end%>
</ul>

app/views/cafes/new.html.erb
<h3 class="name">Add New Cafe</h3>

<%= render partial: 'form' %>

app/views/cafes/show.html.erb
<h3 class="name">
    <%= @cafe.name %>
</h3>
<div class="address">
    <p>
        <%= @cafe.address %>
    </p>
</div>
    <% if @cafe.roaster%>
    <p>
        Coffee Supplier: <%= link_to "#{@cafe.roaster.name}", roaster_path(@cafe.roaster.id) %>
    </p>
    <% end %>
<hr>

<div class="new-review">
    <% if @current_user.present? %>
        <%= link_to "Add new Rating", new_cafe_rating_cafe_path(@cafe) %>
    <% end %>
</div>

<div class="show-visits">
    <p>
        Recent Reviews:
        <%= render @cafe.rating_cafes %>
    </p>
</div>
<hr>
<div class="map">
    <iframe width="600" height="450" style="border:0" loading="lazy" allowfullscreen src="https://www.google.com/maps/embed/v1/place?q=<%= @cafe.address %>&key=AIzaSyCdE635lhPuKadi5SMfYwPrwZkG27OZ-d4"></iframe>
</div>
    <% if @current_user.present? && @current_user.admin %>
        <%= link_to 'Edit', edit_cafe_path(@cafe) %>
        |
        <%= link_to 'Delete', cafe_path(@cafe), method: 'delete' %>
    <% end%>