config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/search' => "pages#search"
  resources :users
  resources :cafes do
    resources :rating_cafes
  end
  resources :roasters do
    resources :roaster_ratings
  end
  get '/login' => 'session#new' # show login form
  post '/login' => 'session#create' # form submits, performs login, redirects
  delete '/login' => 'session#destroy' #logout link goes here, perform logout, redirect
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cafe.rb
class Cafe < ApplicationRecord
    belongs_to :roaster, optional: true
    has_many :rating_cafes
    has_many :users, through: 'cafe_ratings'
end

app/models/cafe_rating.rb
class CafeRating < ApplicationRecord
    belongs_to :user
    belongs_to :cafe
end

app/models/follow.rb
class Follow < ApplicationRecord
    belongs_to :follower, class_name: 'User'
    belongs_to :followed, class_name: 'User'
end

app/models/rating_cafe.rb
class RatingCafe < ApplicationRecord
    belongs_to :user
    belongs_to :cafe
end

app/models/roaster.rb
class Roaster < ApplicationRecord
    has_many :cafes
    has_many :roaster_ratings
    has_many :users, through: 'roaster_ratings'
end

app/models/roaster_rating.rb
class RoasterRating < ApplicationRecord
    belongs_to :user
    belongs_to :roaster
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, uniqueness: true

    has_many :rating_cafes
    has_many :roaster_ratings
    has_many :cafes, through: 'cafe_ratings'
    has_many :roasters, through: 'roaster_ratings'
    has_many :following_relationships, class_name: 'Follow', foreign_key: 'follower_id'
    has_many :followed_relationships, class_name: 'Follow', foreign_key: 'followed_id'

    has_many :following, through: :following_relationships, source: :followed
    has_many :followers, through: :followed_relationships, source: :follower

    def follow_safe other_user
        if self.following.include? other_user
            return false
        else
            self.following << other_user
            return true
        end
    end 

    def following_users
        User.where user: self.following        
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :fetch_user

    def fetch_user
        if session[:user_id].present?
            @current_user = User.find_by id: session[:user_id]
        end # session check

        session[:user_id] = nil unless @current_user.present?
    end # fetch_user()

    def check_if_logged_in
        unless @current_user.present?
            flash[:error] = 'You must log in to perform this action.'
            redirect_to login_path
        end
    end # check_if_logged_in()
end # class ApplicationController

app/controllers/cafes_controller.rb
class CafesController < ApplicationController
  
  before_action :check_if_logged_in, except: [:index, :show]
  
  def new
    @cafe = Cafe.new
  end

  def create
    Cafe.create cafe_params

    redirect_to cafes_path
  end

  def index
    @cafes = Cafe.all
  end

  def show
    @cafe = Cafe.find params[:id]
  end

  def edit
    @cafe = Cafe.find params[:id]
  end

  def update
    cafe = Cafe.find params[:id]
    cafe.update! cafe_params
    redirect_to cafe_path(params[:id])
  end

  def destroy
    Cafe.destroy params[:id]
    redirect_to cafes_path
  end

  private
  def cafe_params
    params.require(:cafe).permit(
      :name,
      :address,
      :roaster_id
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def search
    if params[:search].blank?
      redirect_to root_path and return
    else
      @params = params[:search].downcase
      @matchcafe = Cafe.all.where("lower(name) LIKE ?", "%#{@params}%")
      @matchroaster = Roaster.all.where("lower(name) LIKE ?", "%#{@params}%")
      @matchuser = User.all.where("lower(name) LIKE ?", "%#{@params}%")
    end 
  end
end

app/controllers/roasters_controller.rb
class RoastersController < ApplicationController
  before_action :check_if_logged_in, except: [:index, :show]
  
  def new
    @roaster = Roaster.new
  end

  def create
    Roaster.create roaster_params

    redirect_to roasters_path
  end

  def index
    @roasters = Roaster.all
  end

  def show
    @roaster = Roaster.find params[:id]
  end

  def edit
    @roaster = Roaster.find params[:id]
  end

  def update
    roaster = Roaster.find params[:id]
    roaster.update! roaster_params
    redirect_to roaster_path(params[:id])
  end

  def destroy
    Roaster.destroy params[:id]
    redirect_to roasters_path
  end

  private
  def roaster_params
    params.require(:roaster).permit(
      :name,
      :address
    )
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by email: params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path user.id
    else
      flash[:error] = 'Invalid email or password'
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    
    if params[:user][:photo_url].present?
      response = Cloudinary::Uploader.upload params[:user][:photo_url]
      @user.photo_url = response['public_id']
    end
    
    @user.save
    
    if @user.persisted?
      session[:user_id] = @user.id
      redirect_to users_path
    else
      flash[:error] = 'Invalid email or password'
      render :new
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    user = User.find params[:id]
    user.update! user_params
    redirect_to user_path(params[:id])
  end

  def destroy
    User.destroy params[:id]
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(
      :email,
      :name,
      :city,
      :suburb,
      :photo_url,
      :password,
      :password_confirmation
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cafe_ratings_helper.rb
module CafeRatingsHelper
end

app/helpers/cafes_helper.rb
module CafesHelper
end

app/helpers/roasters_helper.rb
module RoastersHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Brewd</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="nav-banner">
      <h1>
        Brewd.
      </h1>
      <nav>
          <%= link_to 'Home', root_path %>
          <%= link_to 'Cafes', cafes_path %>
          <%= link_to 'Roasters', roasters_path  %>
          <%= link_to 'Users', users_path %>
          <% if @current_user.present? %>
            <%= link_to 'New Cafe', new_cafe_path %>
            <%= link_to 'New Roaster', new_roaster_path %>
          <div id="logout">
            <p>
              Signed in as: <%= link_to "#{@current_user.name}", user_path(@current_user.id) %>
              |
              <%= link_to 'Logout', login_path, method: 'delete' %>
            </p>
          </div>
            <% else %>
              <div id="login">
                <p>
                  <%= link_to 'Login', login_path %>
                  |
                  <%= link_to 'Sign Up', new_user_path %>
                </p>
              </div>
            <% end %>
          </div>
      </nav>
    </header>
    
    <%= yield %>

  </body> 
</html>

app/views/pages/home.html.erb
<h1></h1>


<%= form_tag(search_path, :method => "get") do %>
    <%= search_field_tag :search, params[:search], placeholder: "Search for Cafes, Roasters or Users" %>
    <%= button_tag "Search", class: 'search-button' %>
<% end %>

app/views/pages/search.html.erb
<h3>Search Results</h3>

<% @matchcafe.each do |c| %>
    <%= link_to c.name, cafe_path(c.id) %> - cafe
    <br>
    <hr>
<% end %>

<% @matchroaster.each do |r| %>
    <%= link_to r.name, roaster_path(r.id) %> - roaster
    <br>
    <hr>
<% end %>

<% @matchuser.each do |u| %>
    <%= link_to u.name, user_path(u.id) %> - user
    <br>
    <hr>
<% end %>